require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'QuizAppFrontEnd' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  $RNFirebaseAsStaticFramework = true
    FirebaseSDKVersion = '8.11.0'

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  pod 'RNFBAdMob', :path => '../node_modules/@react-native-firebase/admob'

  target 'QuizAppFrontEndTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!({ 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3' , 'Flipper' => '0.88.0' })
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

